[package]
name = "day04"
description = "Advent of Code 2016 - Day 04"
version = "0.1.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
regex = "1.3"
counter = "0.4.3"