[package]
name = "day05"
description = "Advent of Code 2016 - Day 05"
version = "0.1.0"
authors = ["Sergio de Carvalho <scarvalhojr@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33"
md5 = "0.7.0"